<template>
  <footer class="p-1 text-white bg-black w-full">
    <div class="flex flex-col relative">
      <ul
        v-if="activeLinks"
        class="font-cera-pro grid grid-cols-2 md:grid-cols-4 justify-center gap-2 py-2 flex-wrap items-center text-sm text-gray-500 sm:mt-0 w-full"
      >
        <li class>
          <a
            class="text-white rounded-xl bg-teal-700 py-3 px-3 block"
            :href="
              activeLinks
                ? 'https://cdn.teslaexch.com/images/Domains/Lotus444/HOWTOREGISTER.mp4'
                : 'javascript:;'
            "
            :target="activeLinks ? '_blank' : '_parent'"
            >How To register</a
          >
        </li>
        <li class>
          <a
            class="text-white rounded-xl bg-teal-700 py-3 px-3 block"
            :href="
              activeLinks
                ? 'https://cdn.teslaexch.com/images/Domains/Lotus444/HOWTODEPOSIT.mp4'
                : 'javascript:;'
            "
            :target="activeLinks ? '_blank' : '_parent'"
            >How To deposit</a
          >
        </li>
        <li class>
          <a
            class="text-white rounded-xl bg-teal-700 py-3 px-3 block"
            :href="
              activeLinks
                ? 'https://cdn.teslaexch.com/images/Domains/Lotus444/HOWTOWITHDRAWAL.mp4'
                : 'javascript:;'
            "
            :target="activeLinks ? '_blank' : '_parent'"
            >How To withdrawal</a
          >
        </li>
        <li class>
          <a
            class="text-white rounded-xl bg-teal-700 py-3 px-3 block"
            :href="
              activeLinks
                ? 'https://cdn.teslaexch.com/images/Domains/Lotus444/OURCASINO.mp4'
                : 'javascript:;'
            "
            :target="activeLinks ? '_blank' : '_parent'"
            >Our casino</a
          >
        </li>
      </ul>
      <div
        class="text-center p-2 "
        :class="anyOtherActive? 'items-center grid grid-cols-2 md:grid-cols-3 gap-3':'mx-auto'"
      >
        <a
          v-if="
            $store.getters['configModule/domainSettings']?.showSupportLink
          "
          :href="$store.getters['configModule/domainSettings']?.supportLink"
          target="_blank"
        >
          <div class="h-8 flex justify-center items-center">
            <img src="@/assets/svg/WhatsApp.svg.webp" class="h-10 w-10 mr-2" />

            <h3 class="text-left font-bold text-xs">WHATSAPP NOW!</h3>
          </div>
        </a>
        <a
          v-if="
          $store.getters['configModule/domainSettings']?.telegramId
          "
          :href="$store.getters['configModule/domainSettings']?.telegramId"
          target="_blank"
        >
          <div class="h-8 flex justify-center items-center">
            <img src="@/assets/svg/telegram.svg" class="h-10 w-10 mr-2" />

            <h3 class="text-left font-bold text-xs">TELEGRAM NOW!</h3>
          </div>
        </a>
        <a
          v-if="
          $store.getters['configModule/domainSettings']?.instagramId
          "
          :href="$store.getters['configModule/domainSettings']?.instagramId"
          target="_blank"
        >
          <div class="h-8 flex justify-center items-center">
            <img src="@/assets/svg/instagram.svg" class="h-10 w-10 mr-2" />

            <h3 class="text-left font-bold text-xs">INSTAGRAM NOW!</h3>
          </div>
        </a>
      </div>
      <div class="flex flex-col md:flex-row p-2">
        <a class="min-w-[100px] m-auto p-3" target="_blank"
          ><img src="@/assets/images/gaming.png" alt="gaming"
        /></a>
        <!-- <p class="text-xs">
          LOTUS 365 is operated by Aura Services N.V. a limited liability
          company incorporated under the laws of Curacao with company
          Registration number 156283 with registered office at Abraham de
          Veerstraat 9 , Curacao P.O Box 3421 and is licensed and regulated by
          the Curacao authority as the regulatory body responsible holding a
          (Sub-license with License number 365/JAZ Sub-License
          GLH-OCCHKTW0701162021 granted on 17.01.2021). Players are requested
          not to contact any untrusted sources for LOTUS 365 accounts as this is
          an online site and they can only register independently without any
          agents. Only deposit through the account details generated by the
          system or provided by our official support team.
        </p> -->
      </div>
      <div class="pt-3 grid grid-cols-2 gap-7 md:flex text-center">
        <img
          class="m-auto"
          src="@/assets/svg/upi.b1dbf1b2.svg"
          alt="gaming"
        /><img
          class="m-auto"
          src="@/assets/svg/bankTransfer.ec47485a.svg"
          alt="gaming"
        /><img
          class="m-auto"
          src="@/assets/svg/BeGamble.bde9544d.svg"
          alt="gaming"
        /><img
          class="m-auto"
          src="@/assets/svg/gamblingCom.1cb194a5.svg"
          alt="gaming"
        /><img
          class="m-auto"
          src="@/assets/svg/corga2.985668f6.svg"
          alt="gaming"
        /><img
          class="m-auto"
          src="@/assets/svg/mga.d077581b.svg"
          alt="gaming"
        />
      </div>
    </div>
  </footer>
</template>

<script>
  export default {
    data() {
      return {
        currentRoute: "",
        accountModalIsOpen: false,
      };
    },
    methods: {
      showAccountModal() {
        if (this.accountModalIsOpen == true) {
          this.emitter.emit("show-account-modal", false);
          this.accountModalIsOpen = false;
          return;
        }
        if (this.$store.getters["authModule/userinfo"]) {
          this.emitter.emit("show-account-modal", true);
          this.accountModalIsOpen = true;
        } else {
          this.$router.push("/auth/login");
          this.accountModalIsOpen = false;
        }
      },
      accountModal(e) {
        if (e.target.id == "AccountMenu") {
          return;
        } else {
          this.emitter.emit("show-account-modal", false);
          this.accountModalIsOpen = false;
        }
      },
    },

    computed: {
      anyOtherActive(){
        return (this.$store.getters['configModule/domainSettings']?.instagramId) || (this.$store.getters['configModule/domainSettings']?.telegramId)
      },
      isActiveAccount() {
        if (
          this.currentRoute == "change-password" ||
          this.currentRoute == "bet-history" ||
          this.currentRoute == "open-bets" ||
          this.currentRoute == "profit-loss"
        )
          return true;
        else return false;
      },
      activeLinks() {
        if (window.location.href.includes("lotus444.com")) {
          return true;
        } else return false;
      },
    },

    watch: {
      /*$route: {
        immediate: true,
        handler() {
          this.currentRoute = this.$router.currentRoute._value.name;
        },
      },*/
    },
  };
</script>

<style scoped>
  ul {
    padding-left: 0rem !important;
    margin-bottom: 0rem !important;
  }
</style>
<style>
  nav .main-nav a {
    margin-top: -6.26667vw;
  }
</style>
